// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  call_to_action: dynamic(() => import("./CallToAction")),
  hero_banner: dynamic(() => import("./HeroBanner")),
  image_gallery: dynamic(() => import("./ImageGallery")),
  quote: dynamic(() => import("./Quote")),
  text_section: dynamic(() => import("./TextSection")),
  two_column_layout: dynamic(() => import("./TwoColumnLayout")),
};
