// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

const HeroBanner = dynamic(() => import("./HeroBanner"));
const TextSection = dynamic(() => import("./TextSection"));
const TwoColumnLayout = dynamic(() => import("./TwoColumnLayout"));
const ImageGallery = dynamic(() => import("./ImageGallery"));
const CallToAction = dynamic(() => import("./CallToAction"));
const Quote = dynamic(() => import("./Quote"));

export const components = {
  hero_banner: HeroBanner,
  text_section: TextSection,
  two_column_layout: TwoColumnLayout,
  image_gallery: ImageGallery,
  call_to_action: CallToAction,
  quote: Quote,
};
